# coding: utf-8

"""
    Vouchsafe API docs

    Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.

    The version of the OpenAPI document: 0.1.0
    Contact: help@vouchsafe.id
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouchsafe_python.models.verification import Verification

class TestVerification(unittest.TestCase):
    """Verification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Verification:
        """Test Verification
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Verification`
        """
        model = Verification()
        if include_optional:
            return Verification(
                id = '',
                status = 'InProgress',
                created_at = '',
                expires_at = '',
                email = '',
                redirect_url = '',
                workflow_id = '',
                external_id = ''
            )
        else:
            return Verification(
                id = '',
                status = 'InProgress',
                created_at = '',
                expires_at = '',
                email = '',
                redirect_url = '',
                workflow_id = '',
                external_id = '',
        )
        """

    def testVerification(self):
        """Test Verification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
