# coding: utf-8

"""
    Vouchsafe API docs

    Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.

    The version of the OpenAPI document: 0.1.0
    Contact: help@vouchsafe.id
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouchsafe_python.api.smart_lookups_api import SmartLookupsApi


class TestSmartLookupsApi(unittest.TestCase):
    """SmartLookupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SmartLookupsApi()

    def tearDown(self) -> None:
        pass

    def test_perform_smart_lookup(self) -> None:
        """Test case for perform_smart_lookup

        """
        pass

    def test_search_postcode(self) -> None:
        """Test case for search_postcode

        """
        pass


if __name__ == '__main__':
    unittest.main()
