# coding: utf-8

"""
    Vouchsafe API docs

    Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.

    The version of the OpenAPI document: 0.1.0
    Contact: help@vouchsafe.id
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouchsafe_python.api.verifications_api import VerificationsApi


class TestVerificationsApi(unittest.TestCase):
    """VerificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VerificationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_verification(self) -> None:
        """Test case for get_verification

        """
        pass

    def test_list_verifications(self) -> None:
        """Test case for list_verifications

        """
        pass

    def test_request_verification(self) -> None:
        """Test case for request_verification

        """
        pass


if __name__ == '__main__':
    unittest.main()
