# coding: utf-8

"""
    Vouchsafe API docs

    Vouchsafe offers a REST API to conduct operations programmatically.  You can request and manage verifications, as well as perform smart lookups.  To use the API, you need a client ID and secret from the Vouchsafe dashboard. [Sign up here](https://app.vouchsafe.id/) if you haven't already.  We also have a [video guide](https://www.youtube.com/playlist?list=PLx6V6SSTMuF_ZNWBPnysvwmdIwboLViE8) showing the basics, as well as [SDKs and libraries](https://help.vouchsafe.id/en/articles/12026847-vouchsafe-sdks-and-libraries) for popular languages.

    The version of the OpenAPI document: 0.1.0
    Contact: help@vouchsafe.id
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CheckState(str, Enum):
    """
    CheckState
    """

    """
    allowed enum values
    """
    PASS = 'PASS'
    FAIL = 'FAIL'
    PARTIAL = 'PARTIAL'
    NOT_PERFORMED = 'NOT_PERFORMED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CheckState from a JSON string"""
        return cls(json.loads(json_str))


